### ISSUE TITLE
en-UK is not a valid ISO code, en-GB should be used instead

### ISSUE THREAD

**Issue by Pharap** [MegatonHammer/linkle#63]
`en-UK` is not, and never has been, a valid ISO code. The correct ISO code is `en-GB`.

---

References:
* https://stackoverflow.com/a/7296292
* https://bz.apache.org/bugzilla/show_bug.cgi?id=29517

**Comment by roblabla** [comment]
Woops, that's a README bug. The code actually expects en-GB.
